name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Node.js 01
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.0    
    - name: Use Node.js 21
      uses: actions/setup-node@v6.0.0
      with:
        node-version: 22
        cache: 'npm'    
    - run: npm install      
    - run: npm run start01

  build02:
    name: Run Node.js 02
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.0
    - name: Use Node.js 21
      uses: actions/setup-node@v6.0.0
      with:
        node-version: 22
        cache: 'npm'    
    - run: npm install      
    - run: npm run start02

  build03:
    name: Run Node.js 03
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.0
    - name: Use Node.js 21
      uses: actions/setup-node@v6.0.0
      with:
        node-version: 22
        cache: 'npm'    
    - run: npm install      
    - run: npm run start03